# 모든 엔드포인트를 웹에 노출
# 엔드포인트 : 액츄에이터가 제공하는 기능
# 액츄에이터는 운영 환경에서 서비스할 때 필요한 기능들을 매우 편리하게 사용할 수 있도록 다양한 기능을 제공한다.

management:
  # 특정 엔드포인트(여기서는 shutdown)을 활성화
  endpoint:
    shutdown:
      enabled: true
  # 엑튜에이터 기능을 웹에 노출하지만 특정 엔드포인트(여기서는 shutdown)을 제외
  # 엔드포인트를 활성화하고 노출을 둘다 적용되어야 사용할 수 있다.
  # 여기서 shutdown을 웹에 노출하지 않았으므로 활성화되었지만 사용할 수는 없다.
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "shutdown"